# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          npm ci
          npm run docs:build

      # Deploy it
      - name: ssh-scp-deploy
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          #本地打包后的文件目录
          local: docs/.vitepress/dist
          #上传至远程服务器的目标目录
          remote: /var/www/blog
          #远程服务器的地址
          host: ${{ secrets.REMOTE_HOST }}
          #远程服务器的用户名
          user: ${{ secrets.REMOTE_USERNAME }}
          #远程服务器的密钥（与密码二者选其一）
          password: ${{ secrets.REMOTE_PASSWORD }}
          #上传后执行的脚本
          post_upload: sudo nginx -s reload

      # Deploy it on AliYun
      - name: ssh-scp-deploy
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          #本地打包后的文件目录
          local: docs/.vitepress/dist
          #上传至远程服务器的目标目录
          remote: /var/www/blog
          #远程服务器的地址
          host: ${{ secrets.REMOTE_HOST_ALIYUN }}
          #远程服务器的用户名
          user: ${{ secrets.REMOTE_USERNAME_ALIYUN }}
          #远程服务器的密钥（与密码二者选其一）
          password: ${{ secrets.REMOTE_PASSWORD_ALIYUN }}
          #上传后执行的脚本
          post_upload: sudo nginx -s reload
